name: Build React App pour Hostinger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
      
      - name: Configuration de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Installation des dépendances
        run: npm ci
        
      - name: Build du projet
        run: npm run build
        env:
          CI: false
          VITE_BASE_URL: '/git-deploy/'
          
      - name: Créer le .htaccess avancé
        run: |
          cat > build/.htaccess << 'EOL'
          <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteBase /git-deploy/
            RewriteRule ^index\.html$ - [L]
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_FILENAME} !-l
            RewriteRule . /git-deploy/index.html [L]
          </IfModule>

          # Configuration des types MIME corrects - Méthode 1
          <IfModule mod_mime.c>
            # JavaScript
            AddType application/javascript .js
            AddType application/javascript .mjs
            AddType text/javascript .js .mjs
            
            # JSON
            AddType application/json .json
            
            # CSS
            AddType text/css .css
            
            # HTML
            AddType text/html .html .htm
          </IfModule>

          # Configuration des types MIME - Méthode 2 avec mod_headers
          <IfModule mod_headers.c>
            <FilesMatch "\.js$">
              Header set Content-Type "application/javascript"
            </FilesMatch>
            <FilesMatch "\.mjs$">
              Header set Content-Type "application/javascript"
            </FilesMatch>
            <FilesMatch "\.json$">
              Header set Content-Type "application/json"
            </FilesMatch>
            <FilesMatch "\.css$">
              Header set Content-Type "text/css"
            </FilesMatch>
          </IfModule>

          # Désactivation de toute compression qui pourrait interférer avec les types MIME
          <IfModule mod_deflate.c>
            SetEnv no-gzip 1
          </IfModule>

          # Correction pour certains serveurs qui ajoutent des extensions .txt
          <IfModule mod_actions.c>
            Action application/javascript /git-deploy/index.html
          </IfModule>

          # Définition des permissions de répertoire correctes
          <IfModule mod_autoindex.c>
            Options -Indexes
          </IfModule>

          # Empêcher la mise en cache des fichiers JavaScript pour le débogage
          <IfModule mod_expires.c>
            <FilesMatch "\.js$">
              ExpiresActive On
              ExpiresDefault "access plus 0 seconds"
              Header set Cache-Control "no-store, no-cache, must-revalidate, max-age=0"
            </FilesMatch>
          </IfModule>
          EOL

      - name: Vérifier les permissions des fichiers
        run: |
          chmod -R 644 build/*
          find build -type d -exec chmod 755 {} \;

      - name: Configurer Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
      - name: Pousser le dossier build vers la branche build
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build  # Le dossier à déployer (configuré dans vite.config.ts)
          branch: build  # La branche cible
          clean: true  # Nettoie les fichiers existants
          target-folder: git-deploy  # Spécifie le sous-dossier pour le déploiement